---
- hosts: slaveserver
  become: yes
  become_user: root
  tasks:
  - name: Remove previous installation for Docker then update apt-get cache
    apt:
      name: '{{ app }}'
      #      update_cache: true
      state: absent
    vars:
      app:
      - docker-engine
      - docker
      - docker.io
      - containerd
      - runc
  - name: install preq
    apt:
      name: '{{ app2 }}'
      state: present
    vars:
      app2:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
  - name: Install Certificate
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Adding Docker Reprository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      state: present
      update_cache: true
  - name: Start Docker Installtion
    apt:
      name: '{{ app3 }}'
      state: present
    vars:
      app3:
        - docker-ce
        - docker-ce-cli
        - containerd.io
